package com.megaman.maverick.game.entities.megaman.sprites

import com.badlogic.gdx.utils.ObjectMap
import com.mega.game.engine.common.extensions.gdxArrayOf
import com.mega.game.engine.common.extensions.orderedMapOf
import com.mega.game.engine.common.objects.pairTo
import com.megaman.maverick.game.animations.AnimationDef

object MegamanAnimationDefs {

    const val JETPACK_FRAME_DUR = 0.1f
    const val DEFAULT_FRAME_DUR = 0.125f
    const val CHARGING_FRAME_DUR = 0.0625f

    private val defs = orderedMapOf(
        "Jetpack" pairTo AnimationDef(1, 2, JETPACK_FRAME_DUR),
        "JetpackShoot" pairTo AnimationDef(1, 2, JETPACK_FRAME_DUR),
        "Cartin" pairTo AnimationDef(1, 2, gdxArrayOf(1.5f, 0.15f)),
        "Cartin_Damaged" pairTo AnimationDef(1, 3, 0.05f),
        "Cartin_FullyCharged" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "Cartin_HalfCharged" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "Cartin_Shoot" pairTo AnimationDef(),
        "Cartin_Jump" pairTo AnimationDef(),
        "Cartin_JumpHalfCharged" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "Cartin_JumpFullyCharged" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "Cartin_JumpShoot" pairTo AnimationDef(),
        "Climb" pairTo AnimationDef(1, 2, DEFAULT_FRAME_DUR),
        "Climb_Left" pairTo AnimationDef(1, 2, DEFAULT_FRAME_DUR),
        "ClimbShoot" pairTo AnimationDef(1, 1, DEFAULT_FRAME_DUR),
        "ClimbShoot_Left" pairTo AnimationDef(),
        "ClimbHalfCharging" pairTo AnimationDef(2, 2, CHARGING_FRAME_DUR),
        "ClimbHalfCharging_Left" pairTo AnimationDef(2, 2, CHARGING_FRAME_DUR),
        "ClimbCharging" pairTo AnimationDef(2, 2, CHARGING_FRAME_DUR),
        "ClimbCharging_Left" pairTo AnimationDef(2, 2, CHARGING_FRAME_DUR),
        "FinishClimb" pairTo AnimationDef(),
        "FinishClimb_Left" pairTo AnimationDef(),
        "FinishClimbCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "FinishClimbCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "FinishClimbHalfCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "FinishClimbHalfCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "StillClimb" pairTo AnimationDef(),
        "StillClimb_Left" pairTo AnimationDef(),
        "StillClimbCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "StillClimbCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "StillClimbHalfCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "StillClimbHalfCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "Stand" pairTo AnimationDef(1, 2, gdxArrayOf(1.5f, .15f)),
        "Stand_Left" pairTo AnimationDef(1, 2, gdxArrayOf(1.5f, .15f)),
        "StandCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "StandCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "StandHalfCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "StandHalfCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "StandShoot" pairTo AnimationDef(),
        "StandShoot_Left" pairTo AnimationDef(),
        "Damaged" pairTo AnimationDef(1, 5, .05f),
        "Damaged_Left" pairTo AnimationDef(1, 5, .05f),
        "Run" pairTo AnimationDef(1, 4, DEFAULT_FRAME_DUR),
        "Run_Left" pairTo AnimationDef(1, 4, DEFAULT_FRAME_DUR),
        "RunCharging" pairTo AnimationDef(2, 4, CHARGING_FRAME_DUR),
        "RunCharging_Left" pairTo AnimationDef(2, 4, CHARGING_FRAME_DUR),
        "RunHalfCharging" pairTo AnimationDef(2, 4, CHARGING_FRAME_DUR),
        "RunHalfCharging_Left" pairTo AnimationDef(2, 4, CHARGING_FRAME_DUR),
        "RunShoot" pairTo AnimationDef(1, 4, DEFAULT_FRAME_DUR),
        "RunShoot_Left" pairTo AnimationDef(1, 4, DEFAULT_FRAME_DUR),
        "Jump" pairTo AnimationDef(),
        "Jump_Left" pairTo AnimationDef(),
        "JumpCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "JumpCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "JumpHalfCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "JumpHalfCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "JumpShoot" pairTo AnimationDef(),
        "JumpShoot_Left" pairTo AnimationDef(),
        "Swim" pairTo AnimationDef(),
        "Swim_Left" pairTo AnimationDef(),
        "SwimAttack" pairTo AnimationDef(),
        "SwimAttack_Left" pairTo AnimationDef(),
        "SwimCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "SwimCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "SwimHalfCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "SwimHalfCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "SwimShoot" pairTo AnimationDef(),
        "SwimShoot_Left" pairTo AnimationDef(),
        "WallSlide" pairTo AnimationDef(),
        "WallSlide_Left" pairTo AnimationDef(),
        "WallSlideCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "WallSlideCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "WallSlideHalfCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "WallSlideHalfCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "WallSlideShoot" pairTo AnimationDef(),
        "WallSlideShoot_Left" pairTo AnimationDef(),
        "GroundSlide" pairTo AnimationDef(),
        "GroundSlide_Left" pairTo AnimationDef(),
        "GroundSlideShoot" pairTo AnimationDef(),
        "GroundSlideShoot_Left" pairTo AnimationDef(),
        "GroundSlideCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "GroundSlideCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "GroundSlideHalfCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "GroundSlideHalfCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "AirDash" pairTo AnimationDef(),
        "AirDash_Left" pairTo AnimationDef(),
        "AirDashCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "AirDashCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "AirDashHalfCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "AirDashHalfCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "SlipSlide" pairTo AnimationDef(),
        "SlipSlide_Left" pairTo AnimationDef(),
        "SlipSlideCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "SlipSlideCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "SlipSlideHalfCharging" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "SlipSlideHalfCharging_Left" pairTo AnimationDef(1, 2, CHARGING_FRAME_DUR),
        "SlipSlideShoot" pairTo AnimationDef(),
        "SlipSlideShoot_Left" pairTo AnimationDef(),
    )

    fun get() = defs

    fun get(key: String): AnimationDef = get().get(key)

    fun getKeys(): ObjectMap.Keys<String> = get().keys()
}
