package com.megaman.maverick.game.screens

enum class ScreenEnum {
    SIMPLE_INIT_GAME_SCREEN,
    LOGO_SCREEN,
    MAIN_MENU_SCREEN,
    KEYBOARD_SETTINGS_SCREEN,
    CONTROLLER_SETTINGS_SCREEN,
    LEVEL_SELECT_SCREEN,
    LEVEL_SCREEN,
    WILY_CASTLE_SCREEN,
    SAVE_GAME_SCREEN,
    GAME_OVER_SCREEN,
    CREDITS_SCREEN
}
