package com.megaman.maverick.game.screens

enum class ScreenEnum {
    MAIN_MENU_SCREEN,
    LEVEL_SCREEN,
    EXTRAS_SCREEN,
    VIEW_PASSWORD_SCREEN,
    LOAD_PASSWORD_SCREEN,
    KEYBOARD_SETTINGS_SCREEN,
    CONTROLLER_SETTINGS_SCREEN,
    BOSS_INTRO_SCREEN,
    BOSS_SELECT_SCREEN,
    SIMPLE_INIT_GAME_SCREEN,
    SIMPLE_END_LEVEL_SUCCESSFULLY_SCREEN
}
