package com.megaman.maverick.game.screens

enum class ScreenEnum {
    MAIN_MENU_SCREEN,
    LEVEL_SCREEN,
    SAVE_SCREEN,
    LOAD_GAME_SCREEN,
    KEYBOARD_SETTINGS_SCREEN,
    CONTROLLER_SETTINGS_SCREEN,
    BOSS_INTRO_SCREEN,
    BOSS_SELECT_SCREEN,
    SIMPLE_INIT_GAME_SCREEN,
    SIMPLE_END_LEVEL_SUCCESSFULLY_SCREEN
}
